name: najath_announcements
description: "Najath announcements feature module."
version: 0.0.1

resolution: workspace
publish_to: 'none'

environment:
  sdk: ^3.12.2
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  go_router: ^17.5.0
  intl: 0.20.2
  najath_core:
    path: ../../core
  najath_network:
    path: ../../network
  najath_local_db:
    path: ../../local_db
  najath_auth:
    path: ../../auth
  najath_design_system:
    path: ../../design_system

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
