// Module boundaries mirror the SRS. Keep one file per module so concurrent
// feature branches don't fight over a single schema file.
// Generated by @better-auth/cli — regenerate, don't hand-edit.
export * from './auth';

export * from './identity';
export * from './academics';
export * from './attendance';
export * from './hifz';
export * from './exams';
export * from './leave';
export * from './hostel';
export * from './canteen';
export * from './comms';
